apiVersion: v1
kind: Pod
metadata:
  name: TODO_VYPLN_UNIKATNI_JMENO (lowercase, pomlcka, zadne spec znaky)
  labels:
    app: java-hello-world
spec:
  containers:
    - name: java-app
      image: stibi/java-hello-world
      env:
      - name: MOJE_TEST_ENV
        value: "Hello from the environment"
      - name: FOO
        value: bar
      ports:
        - name: spring
          containerPort: 8080
          protocol: TCP
