apiVersion: apps/v1
kind: Deployment
metadata:
  name: TODO-VYPLN-UNIKATNI-JMENO (lowercase, pomlcka, zadne spec znaky)
spec:
  selector:
    matchLabels:
      app: TODO-STEJNE-JAKO-metadata.name
  replicas: 1
  template:
    metadata:
      labels:
        app: TODO-STEJNE-JAKO-metadata.name
    spec:
      containers:
      - name: java-app
        image: stibi/java-hello-world
        env:
        - name: MOJE_TEST_ENV
          value: "Hello from the pod"
        - name: FOO
          value: bar
        ports:
          - name: spring
            containerPort: 8080
            protocol: TCP
