apiVersion: v1
kind: Service
metadata:
  name: muj-java-helloworld
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 30354
  selector:
    app: muj-java-helloworld
  type: NodePort
