apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "muj-hello-world-chart.fullname" . }}
  namespace: default
subjects:
- kind: ServiceAccount
  name: {{ include "muj-hello-world-chart.serviceAccountName" . }}
  namespace: default
roleRef:
  kind: Role
  name: {{ include "muj-hello-world-chart.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
